// +build integration

package migrationfixtures

import (
	"github.com/docker/distribution/registry/datastore/migrations"
	migrate "github.com/rubenv/sql-migrate"
)

func init() {
	m := &migrations.Migration{Migration: &migrate.Migration{
		Id: "20200319131542_create_configurations_test_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS configurations_test (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                blob_id bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                payload bytea NOT NULL,
                CONSTRAINT pk_configurations_test PRIMARY KEY (id),
                CONSTRAINT fk_configurations_test_blob_id_blobs FOREIGN KEY (blob_id) REFERENCES blobs_test (id) ON DELETE CASCADE,
                CONSTRAINT unique_configurations_test_blob_id UNIQUE (blob_id)
            )`,
			"CREATE INDEX IF NOT EXISTS index_configurations_test_blob_id ON configurations_test (blob_id)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS index_configurations_test_blob_id CASCADE",
			"DROP TABLE IF EXISTS configurations_test CASCADE",
		},
	}}

	allMigrations = append(allMigrations, m)
}
