-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.2
-- PostgreSQL version: 11.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- Database creation must be done outside a multicommand file.
-- These commands were put in this file only as a convenience.
-- -- object: registry | type: DATABASE --
-- -- DROP DATABASE IF EXISTS registry;
-- CREATE DATABASE registry
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'en_US.UTF-8'
-- 	LC_CTYPE = 'en_US.UTF-8'
-- 	TABLESPACE = pg_default
-- 	OWNER = postgres;
-- -- ddl-end --
-- 

-- object: public.repositories | type: TABLE --
-- DROP TABLE IF EXISTS public.repositories CASCADE;
CREATE TABLE public.repositories (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name text NOT NULL,
	path text NOT NULL,
	parent_id bigint,
	created_at timestamp NOT NULL DEFAULT now(),
	deleted_at timestamp,
	CONSTRAINT pk_repositories PRIMARY KEY (id),
	CONSTRAINT uq_repositories_path UNIQUE (path)

);
-- ddl-end --
-- ALTER TABLE public.repositories OWNER TO postgres;
-- ddl-end --

-- object: public.manifest_configurations | type: TABLE --
-- DROP TABLE IF EXISTS public.manifest_configurations CASCADE;
CREATE TABLE public.manifest_configurations (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	media_type text NOT NULL,
	digest_hex bytea NOT NULL,
	size bigint NOT NULL,
	payload json NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	deleted_at timestamp,
	CONSTRAINT pk_manifest_configs PRIMARY KEY (id),
	CONSTRAINT uq_manifest_configurations_digest_hex UNIQUE (digest_hex)

);
-- ddl-end --
-- ALTER TABLE public.manifest_configurations OWNER TO postgres;
-- ddl-end --

-- object: public.manifests | type: TABLE --
-- DROP TABLE IF EXISTS public.manifests CASCADE;
CREATE TABLE public.manifests (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	schema_version integer NOT NULL,
	media_type text NOT NULL,
	digest_hex bytea NOT NULL,
	configuration_id bigint,
	payload json NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	marked_at timestamp,
	deleted_at timestamp,
	CONSTRAINT pk_manifests PRIMARY KEY (id),
	CONSTRAINT uq_manifests_digest_hex UNIQUE (digest_hex)

);
-- ddl-end --
-- ALTER TABLE public.manifests OWNER TO postgres;
-- ddl-end --

-- object: public.layers | type: TABLE --
-- DROP TABLE IF EXISTS public.layers CASCADE;
CREATE TABLE public.layers (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	media_type text NOT NULL,
	digest_hex bytea NOT NULL,
	size bigint NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	marked_at timestamp,
	deleted_at timestamp,
	CONSTRAINT pk_layers PRIMARY KEY (id),
	CONSTRAINT uq_layers_digest_hex UNIQUE (digest_hex)

);
-- ddl-end --
-- ALTER TABLE public.layers OWNER TO postgres;
-- ddl-end --

-- object: public.manifest_layers | type: TABLE --
-- DROP TABLE IF EXISTS public.manifest_layers CASCADE;
CREATE TABLE public.manifest_layers (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	manifest_id bigint NOT NULL,
	layer_id bigint NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	deleted_at timestamp,
	CONSTRAINT pk_manifest_layers PRIMARY KEY (id),
	CONSTRAINT uq_manifest_layers_manifest_id_layer_id UNIQUE (manifest_id,layer_id)

);
-- ddl-end --
-- ALTER TABLE public.manifest_layers OWNER TO postgres;
-- ddl-end --

-- object: public.manifest_lists | type: TABLE --
-- DROP TABLE IF EXISTS public.manifest_lists CASCADE;
CREATE TABLE public.manifest_lists (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	schema_version integer NOT NULL,
	media_type text,
	digest_hex bytea NOT NULL,
	payload json NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	marked_at timestamp,
	deleted_at timestamp,
	CONSTRAINT pk_manifest_lists PRIMARY KEY (id),
	CONSTRAINT uq_manifest_lists_digest_hex UNIQUE (digest_hex)

);
-- ddl-end --
-- ALTER TABLE public.manifest_lists OWNER TO postgres;
-- ddl-end --

-- object: public.manifest_list_items | type: TABLE --
-- DROP TABLE IF EXISTS public.manifest_list_items CASCADE;
CREATE TABLE public.manifest_list_items (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	manifest_list_id bigint NOT NULL,
	manifest_id bigint NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	deleted_at timestamp,
	CONSTRAINT pk_manifest_list_items PRIMARY KEY (id),
	CONSTRAINT uq_manifest_list_items_manifest_list_id_manifest_id UNIQUE (manifest_list_id,manifest_id)

);
-- ddl-end --
-- ALTER TABLE public.manifest_list_items OWNER TO postgres;
-- ddl-end --

-- object: public.tags | type: TABLE --
-- DROP TABLE IF EXISTS public.tags CASCADE;
CREATE TABLE public.tags (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name text NOT NULL,
	repository_id bigint NOT NULL,
	manifest_id bigint,
	manifest_list_id bigint,
	created_at timestamp NOT NULL DEFAULT now(),
	updated_at timestamp,
	deleted_at timestamp,
	CONSTRAINT pk_tags PRIMARY KEY (id),
	CONSTRAINT uq_tags_name_repository_id UNIQUE (name,repository_id),
	CONSTRAINT chk_tags_manifest_id_manifest_list_id CHECK (((manifest_id is not null and manifest_list_id is null) or (manifest_id is null and manifest_list_id is not null)))

);
-- ddl-end --
-- ALTER TABLE public.tags OWNER TO postgres;
-- ddl-end --

-- object: public.repository_manifests | type: TABLE --
-- DROP TABLE IF EXISTS public.repository_manifests CASCADE;
CREATE TABLE public.repository_manifests (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	repository_id bigint NOT NULL,
	manifest_id bigint NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	deleted_at timestamp,
	CONSTRAINT pk_repository_manifests PRIMARY KEY (id),
	CONSTRAINT uq_repository_manifests_repository_id_manifest_id UNIQUE (repository_id,manifest_id)

);
-- ddl-end --
-- ALTER TABLE public.repository_manifests OWNER TO postgres;
-- ddl-end --

-- object: public.repository_manifest_lists | type: TABLE --
-- DROP TABLE IF EXISTS public.repository_manifest_lists CASCADE;
CREATE TABLE public.repository_manifest_lists (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	repository_id bigint NOT NULL,
	manifest_list_id bigint NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	deleted_at timestamp,
	CONSTRAINT pk_repository_manifest_lists PRIMARY KEY (id),
	CONSTRAINT uq_repository_manifests_repository_id_manifest_list_id UNIQUE (repository_id,manifest_list_id)

);
-- ddl-end --
-- ALTER TABLE public.repository_manifest_lists OWNER TO postgres;
-- ddl-end --

-- object: tags_repository_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.tags_repository_id_fkey CASCADE;
CREATE INDEX tags_repository_id_fkey ON public.tags
	USING btree
	(
	  repository_id
	);
-- ddl-end --

-- object: tags_manifest_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.tags_manifest_id_fkey CASCADE;
CREATE INDEX tags_manifest_id_fkey ON public.tags
	USING btree
	(
	  manifest_id
	);
-- ddl-end --

-- object: repositories_parent_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.repositories_parent_id_fkey CASCADE;
CREATE INDEX repositories_parent_id_fkey ON public.repositories
	USING btree
	(
	  parent_id
	);
-- ddl-end --

-- object: manifest_layers_manifest_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.manifest_layers_manifest_id_fkey CASCADE;
CREATE INDEX manifest_layers_manifest_id_fkey ON public.manifest_layers
	USING btree
	(
	  manifest_id
	);
-- ddl-end --

-- object: manifest_layers_layer_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.manifest_layers_layer_id_fkey CASCADE;
CREATE INDEX manifest_layers_layer_id_fkey ON public.manifest_layers
	USING btree
	(
	  layer_id
	);
-- ddl-end --

-- object: manifest_list_items_manifest_list_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.manifest_list_items_manifest_list_id_fkey CASCADE;
CREATE INDEX manifest_list_items_manifest_list_id_fkey ON public.manifest_list_items
	USING btree
	(
	  manifest_list_id
	);
-- ddl-end --

-- object: manifest_list_items_manifest_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.manifest_list_items_manifest_id_fkey CASCADE;
CREATE INDEX manifest_list_items_manifest_id_fkey ON public.manifest_list_items
	USING btree
	(
	  manifest_id
	);
-- ddl-end --

-- object: tags_manifest_list_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.tags_manifest_list_id_fkey CASCADE;
CREATE INDEX tags_manifest_list_id_fkey ON public.tags
	USING btree
	(
	  manifest_list_id
	);
-- ddl-end --

-- object: repository_manifests_repository_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.repository_manifests_repository_id_fkey CASCADE;
CREATE INDEX repository_manifests_repository_id_fkey ON public.repository_manifests
	USING btree
	(
	  repository_id
	);
-- ddl-end --

-- object: repository_manifests_manifest_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.repository_manifests_manifest_id_fkey CASCADE;
CREATE INDEX repository_manifests_manifest_id_fkey ON public.repository_manifests
	USING btree
	(
	  manifest_id
	);
-- ddl-end --

-- object: repository_manifest_lists_repository_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.repository_manifest_lists_repository_id_fkey CASCADE;
CREATE INDEX repository_manifest_lists_repository_id_fkey ON public.repository_manifest_lists
	USING btree
	(
	  repository_id
	);
-- ddl-end --

-- object: repository_manifest_lists_manifest_list_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.repository_manifest_lists_manifest_list_id_fkey CASCADE;
CREATE INDEX repository_manifest_lists_manifest_list_id_fkey ON public.repository_manifest_lists
	USING btree
	(
	  manifest_list_id
	);
-- ddl-end --

-- object: manifests_configuration_id_fkey | type: INDEX --
-- DROP INDEX IF EXISTS public.manifests_configuration_id_fkey CASCADE;
CREATE INDEX manifests_configuration_id_fkey ON public.manifests
	USING btree
	(
	  configuration_id
	);
-- ddl-end --

-- object: fk_repositories_parent_id | type: CONSTRAINT --
-- ALTER TABLE public.repositories DROP CONSTRAINT IF EXISTS fk_repositories_parent_id CASCADE;
ALTER TABLE public.repositories ADD CONSTRAINT fk_repositories_parent_id FOREIGN KEY (parent_id)
REFERENCES public.repositories (id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_manifests_configuration_id | type: CONSTRAINT --
-- ALTER TABLE public.manifests DROP CONSTRAINT IF EXISTS fk_manifests_configuration_id CASCADE;
ALTER TABLE public.manifests ADD CONSTRAINT fk_manifests_configuration_id FOREIGN KEY (configuration_id)
REFERENCES public.manifest_configurations (id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_manifest_layers_manifest_id | type: CONSTRAINT --
-- ALTER TABLE public.manifest_layers DROP CONSTRAINT IF EXISTS fk_manifest_layers_manifest_id CASCADE;
ALTER TABLE public.manifest_layers ADD CONSTRAINT fk_manifest_layers_manifest_id FOREIGN KEY (manifest_id)
REFERENCES public.manifests (id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_manifest_layers_layer_id | type: CONSTRAINT --
-- ALTER TABLE public.manifest_layers DROP CONSTRAINT IF EXISTS fk_manifest_layers_layer_id CASCADE;
ALTER TABLE public.manifest_layers ADD CONSTRAINT fk_manifest_layers_layer_id FOREIGN KEY (layer_id)
REFERENCES public.layers (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_manifest_list_items_manifest_list_id | type: CONSTRAINT --
-- ALTER TABLE public.manifest_list_items DROP CONSTRAINT IF EXISTS fk_manifest_list_items_manifest_list_id CASCADE;
ALTER TABLE public.manifest_list_items ADD CONSTRAINT fk_manifest_list_items_manifest_list_id FOREIGN KEY (manifest_list_id)
REFERENCES public.manifest_lists (id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_manifest_list_items_manifest_id | type: CONSTRAINT --
-- ALTER TABLE public.manifest_list_items DROP CONSTRAINT IF EXISTS fk_manifest_list_items_manifest_id CASCADE;
ALTER TABLE public.manifest_list_items ADD CONSTRAINT fk_manifest_list_items_manifest_id FOREIGN KEY (manifest_id)
REFERENCES public.manifests (id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_tags_repository_id | type: CONSTRAINT --
-- ALTER TABLE public.tags DROP CONSTRAINT IF EXISTS fk_tags_repository_id CASCADE;
ALTER TABLE public.tags ADD CONSTRAINT fk_tags_repository_id FOREIGN KEY (repository_id)
REFERENCES public.repositories (id) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_tags_manifest_id | type: CONSTRAINT --
-- ALTER TABLE public.tags DROP CONSTRAINT IF EXISTS fk_tags_manifest_id CASCADE;
ALTER TABLE public.tags ADD CONSTRAINT fk_tags_manifest_id FOREIGN KEY (manifest_id)
REFERENCES public.manifests (id) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_tags_manifest_list_id | type: CONSTRAINT --
-- ALTER TABLE public.tags DROP CONSTRAINT IF EXISTS fk_tags_manifest_list_id CASCADE;
ALTER TABLE public.tags ADD CONSTRAINT fk_tags_manifest_list_id FOREIGN KEY (manifest_list_id)
REFERENCES public.manifest_lists (id) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_repository_manifests_repository_id | type: CONSTRAINT --
-- ALTER TABLE public.repository_manifests DROP CONSTRAINT IF EXISTS fk_repository_manifests_repository_id CASCADE;
ALTER TABLE public.repository_manifests ADD CONSTRAINT fk_repository_manifests_repository_id FOREIGN KEY (repository_id)
REFERENCES public.repositories (id) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_repository_manifests_manifest_id | type: CONSTRAINT --
-- ALTER TABLE public.repository_manifests DROP CONSTRAINT IF EXISTS fk_repository_manifests_manifest_id CASCADE;
ALTER TABLE public.repository_manifests ADD CONSTRAINT fk_repository_manifests_manifest_id FOREIGN KEY (manifest_id)
REFERENCES public.manifests (id) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_repository_manifest_lists_repository_id | type: CONSTRAINT --
-- ALTER TABLE public.repository_manifest_lists DROP CONSTRAINT IF EXISTS fk_repository_manifest_lists_repository_id CASCADE;
ALTER TABLE public.repository_manifest_lists ADD CONSTRAINT fk_repository_manifest_lists_repository_id FOREIGN KEY (repository_id)
REFERENCES public.repositories (id) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_repository_manifest_lists_manifest_list_id | type: CONSTRAINT --
-- ALTER TABLE public.repository_manifest_lists DROP CONSTRAINT IF EXISTS fk_repository_manifest_lists_manifest_list_id CASCADE;
ALTER TABLE public.repository_manifest_lists ADD CONSTRAINT fk_repository_manifest_lists_manifest_list_id FOREIGN KEY (manifest_list_id)
REFERENCES public.manifest_lists (id) MATCH FULL
ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --
