BEGIN;
DROP INDEX IF EXISTS ix_repositories_parent_id;
DROP INDEX IF EXISTS ix_manifest_layers_manifest_id;
DROP INDEX IF EXISTS ix_manifest_layers_layer_id;
DROP INDEX IF EXISTS ix_manifest_list_manifests_manifest_list_id;
DROP INDEX IF EXISTS ix_manifest_list_manifests_manifest_id;
DROP INDEX IF EXISTS ix_tags_repository_id;
DROP INDEX IF EXISTS ix_tags_manifest_id;
DROP INDEX IF EXISTS ix_tags_manifest_list_id;
DROP INDEX IF EXISTS ix_repository_manifests_repository_id;
DROP INDEX IF EXISTS ix_repository_manifests_manifest_id;
DROP INDEX IF EXISTS ix_repository_manifest_lists_repository_id;
DROP INDEX IF EXISTS ix_repository_manifest_lists_manifest_list_id;
COMMIT;