package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200408192311_create_repository_manifests_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS repository_manifests (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                repository_id bigint NOT NULL,
                manifest_id bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                CONSTRAINT pk_repository_manifests PRIMARY KEY (id),
                CONSTRAINT fk_repository_manifests_repository_id_repositories FOREIGN KEY (repository_id) REFERENCES repositories (id) ON DELETE CASCADE,
                CONSTRAINT fk_repository_manifests_manifest_id_manifests FOREIGN KEY (manifest_id) REFERENCES manifests (id) ON DELETE CASCADE,
                CONSTRAINT uq_repository_manifests_repository_id_manifest_id UNIQUE (repository_id, manifest_id)
            )`,
			"CREATE INDEX IF NOT EXISTS ix_repository_manifests_repository_id ON repository_manifests (repository_id)",
			"CREATE INDEX IF NOT EXISTS ix_repository_manifests_manifest_id ON repository_manifests (manifest_id)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_repository_manifests_manifest_id CASCADE",
			"DROP INDEX IF EXISTS ix_repository_manifests_repository_id CASCADE",
			"DROP TABLE IF EXISTS repository_manifests CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
