CREATE TABLE IF NOT EXISTS manifest_lists
(
    id             bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    schema_version integer   NOT NULL,
    media_type     text,
    digest_hex     bytea     NOT NULL,
    payload        json      NOT NULL,
    created_at     timestamp with time zone NOT NULL DEFAULT now(),
    marked_at      timestamp with time zone,
    deleted_at     timestamp with time zone,
    CONSTRAINT pk_manifest_lists PRIMARY KEY (id),
    CONSTRAINT uq_manifest_lists_digest_hex UNIQUE (digest_hex)
);