package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200319131907_create_manifest_lists_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS manifest_lists (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                marked_at timestamp WITH time zone,
                schema_version integer NOT NULL,
                digest_algorithm smallint NOT NULL,
                digest_hex bytea NOT NULL,
                payload bytea NOT NULL,
                media_type text,
                CONSTRAINT pk_manifest_lists PRIMARY KEY (id),
                CONSTRAINT uq_manifest_lists_digest_algorithm_digest_hex UNIQUE (digest_algorithm,digest_hex),
                CONSTRAINT ck_manifest_lists_digest_algorithm_enum CHECK ((digest_algorithm IN (1, 2))),
                CONSTRAINT ck_manifest_lists_media_type_length CHECK ((char_length(media_type) <= 255))
            )`,
		},
		Down: []string{
			"DROP TABLE IF EXISTS manifest_lists CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
