package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200319131542_create_layers_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS layers (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                size bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                marked_at timestamp WITH time zone,
                digest_hex bytea NOT NULL,
                media_type text NOT NULL,
                CONSTRAINT pk_layers PRIMARY KEY (id),
                CONSTRAINT uq_layers_digest_hex UNIQUE (digest_hex),
                CONSTRAINT ck_layers_media_type_length CHECK ((char_length(media_type) <= 255))
            )`,
		},
		Down: []string{
			"DROP TABLE IF EXISTS layers CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
