package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200319130108_create_manifests_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS manifests (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                marked_at timestamp WITH time zone,
                schema_version integer NOT NULL,
                digest_hex bytea NOT NULL,
                payload bytea NOT NULL,
                media_type text NOT NULL,
                CONSTRAINT pk_manifests PRIMARY KEY (id),
                CONSTRAINT uq_manifests_digest_hex UNIQUE (digest_hex),
                CONSTRAINT ck_manifests_media_type_length CHECK ((char_length(media_type) <= 255))
            )`,
		},
		Down: []string{
			"DROP TABLE IF EXISTS manifests CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
