CREATE TABLE IF NOT EXISTS manifests
(
    id               bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    schema_version   integer   NOT NULL,
    media_type       text      NOT NULL,
    digest_hex       bytea     NOT NULL,
    configuration_id bigint,
    payload          bytea     NOT NULL,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    marked_at        timestamp with time zone,
    deleted_at       timestamp with time zone,
    CONSTRAINT pk_manifests PRIMARY KEY (id),
    CONSTRAINT fk_manifests_configuration_id FOREIGN KEY (configuration_id)
        REFERENCES manifest_configurations (id) ON DELETE CASCADE,
    CONSTRAINT uq_manifests_digest_hex UNIQUE (digest_hex)
);