CREATE TABLE IF NOT EXISTS repositories
(
    id         bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_id  bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name       text                     NOT NULL,
    path       text                     NOT NULL,
    CONSTRAINT pk_repositories PRIMARY KEY (id),
    CONSTRAINT fk_repositories_parent_id_repositories FOREIGN KEY (parent_id)
        REFERENCES repositories (id) ON DELETE CASCADE,
    CONSTRAINT uq_repositories_path UNIQUE (path),
    CONSTRAINT ck_repositories_name_length CHECK ((char_length(name) <= 255)),
    CONSTRAINT ck_repositories_path_length CHECK ((char_length(path) <= 255))
);