CREATE TABLE IF NOT EXISTS repository_manifests
(
    id            bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint                   NOT NULL,
    manifest_id   bigint                   NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at    timestamp with time zone,
    CONSTRAINT pk_repository_manifests PRIMARY KEY (id),
    CONSTRAINT fk_repository_manifests_repository_id FOREIGN KEY (repository_id)
        REFERENCES repositories (id) ON DELETE CASCADE,
    CONSTRAINT fk_repository_manifests_manifest_id FOREIGN KEY (manifest_id)
        REFERENCES manifests (id) ON DELETE CASCADE,
    CONSTRAINT uq_repository_manifests_repository_id_manifest_id UNIQUE (repository_id, manifest_id)
)