package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200408193126_create_repository_manifest_lists_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS repository_manifest_lists (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                repository_id bigint NOT NULL,
                manifest_list_id bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT NOW(),
                CONSTRAINT pk_repository_manifest_lists PRIMARY KEY (id),
                CONSTRAINT fk_repository_manifest_lists_repository_id_repositories FOREIGN KEY (repository_id) REFERENCES repositories (id) ON DELETE CASCADE,
                CONSTRAINT fk_repository_manifest_lists_manifest_list_id_manifest_lists FOREIGN KEY (manifest_list_id) REFERENCES manifest_lists (id) ON DELETE CASCADE,
                CONSTRAINT uq_repository_manifests_repository_id_manifest_list_id UNIQUE (repository_id, manifest_list_id)
            )`,
			"CREATE INDEX IF NOT EXISTS ix_repository_manifest_lists_repository_id ON repository_manifest_lists (repository_id)",
			"CREATE INDEX IF NOT EXISTS ix_repository_manifest_lists_manifest_list_id ON repository_manifest_lists (manifest_list_id)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_repository_manifest_lists_manifest_list_id CASCADE",
			"DROP INDEX IF EXISTS ix_repository_manifest_lists_repository_id CASCADE",
			"DROP TABLE IF EXISTS repository_manifest_lists CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
