BEGIN;
CREATE INDEX IF NOT EXISTS repositories_parent_id_fkey ON repositories (parent_id);
CREATE INDEX IF NOT EXISTS manifests_configuration_id_fkey ON manifests (configuration_id);
CREATE INDEX IF NOT EXISTS manifest_layers_manifest_id_fkey ON manifest_layers (manifest_id);
CREATE INDEX IF NOT EXISTS manifest_layers_layer_id_fkey ON manifest_layers (layer_id);
CREATE INDEX IF NOT EXISTS manifest_list_items_manifest_list_id_fkey ON manifest_list_items (manifest_list_id);
CREATE INDEX IF NOT EXISTS manifest_list_items_manifest_id_fkey ON manifest_list_items (manifest_id);
CREATE INDEX IF NOT EXISTS tags_repository_id_fkey ON tags (repository_id);
CREATE INDEX IF NOT EXISTS tags_manifest_id_fkey ON tags (manifest_id);
CREATE INDEX IF NOT EXISTS tags_manifest_list_id_fkey ON tags (manifest_list_id);
CREATE INDEX IF NOT EXISTS repository_manifests_repository_id_fkey ON repository_manifests (repository_id);
CREATE INDEX IF NOT EXISTS repository_manifests_manifest_id_fkey ON repository_manifests (manifest_id);
CREATE INDEX IF NOT EXISTS repository_manifest_lists_repository_id_fkey ON repository_manifest_lists (repository_id);
CREATE INDEX IF NOT EXISTS repository_manifest_lists_manifest_list_id_fkey ON repository_manifest_lists (manifest_list_id);
COMMIT;