package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200319132010_create_manifest_list_manifests_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS manifest_list_manifests (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                manifest_list_id bigint NOT NULL,
                manifest_id bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                CONSTRAINT pk_manifest_list_manifests PRIMARY KEY (id),
                CONSTRAINT fk_manifest_list_manifests_manifest_list_id_manifest_lists FOREIGN KEY (manifest_list_id) REFERENCES manifest_lists (id) ON DELETE CASCADE,
                CONSTRAINT fk_manifest_list_manifests_manifest_id_manifests FOREIGN KEY (manifest_id) REFERENCES manifests (id) ON DELETE CASCADE,
                CONSTRAINT uq_manifest_list_manifests_manifest_list_id_manifest_id UNIQUE (manifest_list_id, manifest_id)
            )`,
			"CREATE INDEX IF NOT EXISTS ix_manifest_list_manifests_manifest_list_id ON manifest_list_manifests (manifest_list_id)",
			"CREATE INDEX IF NOT EXISTS ix_manifest_list_manifests_manifest_id ON manifest_list_manifests (manifest_id)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_manifest_list_manifests_manifest_id CASCADE",
			"DROP INDEX IF EXISTS ix_manifest_list_manifests_manifest_list_id CASCADE",
			"DROP TABLE IF EXISTS manifest_list_manifests CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
