CREATE TABLE IF NOT EXISTS layers
(
    id         bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    media_type text      NOT NULL,
    digest_hex bytea     NOT NULL,
    size       bigint    NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    marked_at  timestamp,
    deleted_at timestamp,
    CONSTRAINT pk_layers PRIMARY KEY (id),
    CONSTRAINT uq_layers_digest_hex UNIQUE (digest_hex)
);