package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &Migration{Migration: &migrate.Migration{
		Id: "20200319130108_create_blobs_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS blobs (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                size bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                marked_at timestamp WITH time zone,
                digest bytea NOT NULL,
                media_type text NOT NULL,
                CONSTRAINT pk_blobs PRIMARY KEY (id),
                CONSTRAINT uq_blobs_digest UNIQUE (digest),
                CONSTRAINT ck_blobs_media_type_length CHECK ((char_length(media_type) <= 255))
            )`,
		},
		Down: []string{
			"DROP TABLE IF EXISTS blobs CASCADE",
		},
	}}

	allMigrations = append(allMigrations, m)
}
