CREATE TABLE IF NOT EXISTS repositories
(
    id         bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       text      NOT NULL,
    path       text      NOT NULL,
    parent_id  bigint,
    created_at timestamp NOT NULL DEFAULT now(),
    deleted_at timestamp,
    CONSTRAINT pk_repositories PRIMARY KEY (id),
    CONSTRAINT fk_repositories_parent_id FOREIGN KEY (parent_id)
        REFERENCES repositories (id) ON DELETE CASCADE,
    CONSTRAINT uq_repositories_path UNIQUE (path)
);