package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &Migration{Migration: &migrate.Migration{
		Id: "20200319132237_create_tags_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS tags (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                repository_id bigint NOT NULL,
                manifest_id bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                updated_at timestamp WITH time zone,
                name text NOT NULL,
                CONSTRAINT pk_tags PRIMARY KEY (id),
                CONSTRAINT fk_tags_repository_id_repositories FOREIGN KEY (repository_id) REFERENCES repositories (id) ON DELETE CASCADE,
                CONSTRAINT fk_tags_manifest_id_manifests FOREIGN KEY (manifest_id) REFERENCES manifests (id) ON DELETE CASCADE,
                CONSTRAINT uq_tags_name_repository_id UNIQUE (name, repository_id),
                CONSTRAINT ck_tags_name_length CHECK ((char_length(name) <= 255))
            )`,
			"CREATE INDEX IF NOT EXISTS ix_tags_repository_id ON tags (repository_id)",
			"CREATE INDEX IF NOT EXISTS ix_tags_manifest_id ON tags (manifest_id)",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_tags_manifest_id CASCADE",
			"DROP INDEX IF EXISTS ix_tags_repository_id CASCADE",
			"DROP TABLE IF EXISTS tags CASCADE",
		},
	}}

	allMigrations = append(allMigrations, m)
}
