BEGIN;
CREATE INDEX IF NOT EXISTS ix_repositories_parent_id ON repositories (parent_id);
CREATE INDEX IF NOT EXISTS ix_manifest_layers_manifest_id ON manifest_layers (manifest_id);
CREATE INDEX IF NOT EXISTS ix_manifest_layers_layer_id ON manifest_layers (layer_id);
CREATE INDEX IF NOT EXISTS ix_manifest_list_manifests_manifest_list_id ON manifest_list_manifests (manifest_list_id);
CREATE INDEX IF NOT EXISTS ix_manifest_list_manifests_manifest_id ON manifest_list_manifests (manifest_id);
CREATE INDEX IF NOT EXISTS ix_tags_repository_id ON tags (repository_id);
CREATE INDEX IF NOT EXISTS ix_tags_manifest_id ON tags (manifest_id);
CREATE INDEX IF NOT EXISTS ix_tags_manifest_list_id ON tags (manifest_list_id);
CREATE INDEX IF NOT EXISTS ix_repository_manifests_repository_id ON repository_manifests (repository_id);
CREATE INDEX IF NOT EXISTS ix_repository_manifests_manifest_id ON repository_manifests (manifest_id);
CREATE INDEX IF NOT EXISTS ix_repository_manifest_lists_repository_id ON repository_manifest_lists (repository_id);
CREATE INDEX IF NOT EXISTS ix_repository_manifest_lists_manifest_list_id ON repository_manifest_lists (manifest_list_id);
COMMIT;