package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200319131542_create_manifests_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS manifests (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				configuration_id bigint,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                marked_at timestamp WITH time zone,
                schema_version integer NOT NULL,
                digest bytea NOT NULL,
                payload bytea NOT NULL,
                media_type text NOT NULL,
                CONSTRAINT pk_manifests PRIMARY KEY (id),
                CONSTRAINT fk_manifests_configuration_id_configurations FOREIGN KEY (configuration_id) REFERENCES configurations (id) ON DELETE CASCADE,
                CONSTRAINT uq_manifests_digest UNIQUE (digest),
                CONSTRAINT ck_manifests_media_type_length CHECK ((char_length(media_type) <= 255))
            )`,
			"CREATE INDEX IF NOT EXISTS ix_manifests_configuration_id ON manifests (configuration_id) WHERE configuration_id IS NOT NULL",
		},
		Down: []string{
			"DROP INDEX IF EXISTS ix_manifests_configuration_id CASCADE",
			"DROP TABLE IF EXISTS manifests CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
