CREATE TABLE IF NOT EXISTS manifest_configurations
(
    id         bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    media_type text      NOT NULL,
    digest_hex bytea     NOT NULL,
    size       bigint    NOT NULL,
    payload    bytea     NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT pk_manifest_configs PRIMARY KEY (id),
    CONSTRAINT uq_manifest_configurations_digest_hex UNIQUE (digest_hex)
);