CREATE TABLE IF NOT EXISTS repositories
(
    id         bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       text                     NOT NULL,
    path       text                     NOT NULL,
    parent_id  bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT pk_repositories PRIMARY KEY (id),
    CONSTRAINT fk_repositories_parent_id FOREIGN KEY (parent_id)
        REFERENCES repositories (id) ON DELETE CASCADE,
    CONSTRAINT uq_repositories_path UNIQUE (path),
    CONSTRAINT chk_repositories_name CHECK ((char_length(name) <= 255)),
    CONSTRAINT chk_repositories_path CHECK ((char_length(path) <= 255))
);