CREATE TABLE IF NOT EXISTS repository_layers
(
    id            bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    repository_id bigint                   NOT NULL,
    layer_id      bigint                   NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at    timestamp with time zone,
    CONSTRAINT pk_repository_layers PRIMARY KEY (id),
    CONSTRAINT fk_repository_layers_repository_id_repositories FOREIGN KEY (repository_id)
        REFERENCES repositories (id) ON DELETE CASCADE,
    CONSTRAINT fk_repository_layers_layer_id_layers FOREIGN KEY (layer_id)
        REFERENCES layers (id) ON DELETE CASCADE,
    CONSTRAINT uq_repository_layers_repository_id_layer_id UNIQUE (repository_id, layer_id)
);