package migrations

import migrate "github.com/rubenv/sql-migrate"

func init() {
	m := &migrate.Migration{
		Id: "20200319131222_create_manifest_configurations_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS manifest_configurations (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                manifest_id bigint NOT NULL,
                size bigint NOT NULL,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                digest_hex bytea NOT NULL,
                payload bytea NOT NULL,
                media_type text NOT NULL,
                CONSTRAINT pk_manifest_configurations PRIMARY KEY (id),
                CONSTRAINT fk_manifest_configurations_manifest_id_manifests FOREIGN KEY (manifest_id) REFERENCES manifests (id) ON DELETE CASCADE,
                CONSTRAINT uq_manifest_configurations_digest_hex UNIQUE (digest_hex),
                CONSTRAINT uq_manifest_configurations_manifest_id UNIQUE (manifest_id),
                CONSTRAINT ck_manifest_configurations_media_type_length CHECK ((char_length(media_type) <= 255))
            )`,
		},
		Down: []string{
			"DROP TABLE IF EXISTS manifest_configurations CASCADE",
		},
	}

	allMigrations = append(allMigrations, m)
}
