// +build integration

package migrationfixtures

import (
	"github.com/docker/distribution/migrations"
	migrate "github.com/rubenv/sql-migrate"
)

func init() {
	m := &migrations.Migration{Migration: &migrate.Migration{
		Id: "20200319131542_create_manifests_test_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS manifests_test (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
				configuration_id bigint,
                created_at timestamp WITH time zone NOT NULL DEFAULT now(),
                marked_at timestamp WITH time zone,
                schema_version integer NOT NULL,
                digest bytea NOT NULL,
                payload bytea NOT NULL,
                media_type text NOT NULL,
                CONSTRAINT pk_manifests_test PRIMARY KEY (id),
                CONSTRAINT fk_manifests_test_configuration_id_configurations FOREIGN KEY (configuration_id) REFERENCES configurations_test (id) ON DELETE CASCADE,
                CONSTRAINT unique_manifests_test_digest UNIQUE (digest),
                CONSTRAINT check_manifests_test_media_type_length CHECK ((char_length(media_type) <= 255))
            )`,
			"CREATE INDEX IF NOT EXISTS index_manifests_test_configuration_id ON manifests_test (configuration_id) WHERE configuration_id IS NOT NULL",
		},
		Down: []string{
			"DROP INDEX IF EXISTS index_manifests_test_configuration_id CASCADE",
			"DROP TABLE IF EXISTS manifests_test CASCADE",
		},
	}}

	allMigrations = append(allMigrations, m)
}
