// +build integration

package migrationfixtures

import (
	"github.com/docker/distribution/migrations"
	migrate "github.com/rubenv/sql-migrate"
)

func init() {
	m := &migrations.Migration{Migration: &migrate.Migration{
		Id: "20201027124302_create_post_migration_test_two_table",
		Up: []string{
			`CREATE TABLE IF NOT EXISTS test_two (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                value text NOT NULL,
                CONSTRAINT pk_test_two PRIMARY KEY (id)
            )`,
		},
		Down: []string{
			"DROP TABLE IF EXISTS test_two CASCADE",
		},
	},
		PostDeployment: true,
	}

	allMigrations = append(allMigrations, m)
}
